/* Generated by ledger.build-contract. Do not edit. */
export type LedgerRoot = string;

export interface DeveloperHead {
  network: string;
  height: number;
  block_root: LedgerRoot;
  state_root: LedgerRoot;
}

export interface DeveloperAccount {
  address: string;
  address_root: LedgerRoot;
  block_root: LedgerRoot;
  state_root: LedgerRoot;
}

export interface DeveloperSubmission {
  transaction_root: LedgerRoot;
  receipt_root: LedgerRoot;
  block_root: LedgerRoot;
  state_root: LedgerRoot;
  status: "ok" | "error";
}

export interface SignedRegistrationRequest {
  public_key: string;
  signing_payload: string;
}

export interface SignedAccount {
  address: LedgerRoot;
  public_key: string;
  block_root: LedgerRoot;
  state_root: LedgerRoot;
}

export interface SignedIntegerRequest {
  address: LedgerRoot;
  sequence: number;
  signing_payload: string;
}

export interface SignedSubmission extends DeveloperSubmission {
  address: LedgerRoot;
}

export interface DocumentHead {
  document_id: string;
  head_revision: LedgerRoot;
  syntax_root: LedgerRoot;
  next_order: number;
}

export interface SignedDocumentRequest {
  signing_payload: string;
}

export interface OfflineDocumentSubmission {
  documentId: string;
  nodeId: string;
  baseRevision?: LedgerRoot;
  syntaxRoot?: LedgerRoot;
  operationRoot?: LedgerRoot;
  publicKey: string;
  signature: string;
  packHex: string;
  cellCount: number;
}

export interface OfflineTransactionSubmission {
  network: string;
  sequence: number;
  operationRoot: LedgerRoot;
  formRoot: LedgerRoot;
  transactionRoot: LedgerRoot;
  runtimeRoot: LedgerRoot;
  publicKey: string;
  signature: string;
  costLimit: number;
  packHex: string;
  cellCount: number;
  operationManifest: Array<{
    root: LedgerRoot;
    kind: string;
    valueRoot?: LedgerRoot;
    symbolRoot?: LedgerRoot;
    depth?: number;
    index?: number;
    functionRoot?: LedgerRoot;
    childRoots: LedgerRoot[];
  }>;
  primitiveManifest: Array<{ root: LedgerRoot; id: string; arity: number }>;
}

export type DocumentOperation =
  | { kind: "text.splice"; target: string; offset: number; deleteCount: number; text: string }
  | { kind: "node.insert"; parent: string; before?: string; after?: string; nodeRoot: LedgerRoot }
  | { kind: "node.delete"; target: string; expectedRoot: LedgerRoot }
  | { kind: "node.move"; target: string; parent: string; before?: string; after?: string }
  | { kind: "node.replace"; target: string; expectedRoot: LedgerRoot; nodeRoot: LedgerRoot }
  | { kind: "node.set-attrs"; target: string; expectedAttrsRoot: LedgerRoot; attrsRoot: LedgerRoot }
  | { kind: "mark.add" | "mark.remove"; target: string; from: number; to: number; markRoot: LedgerRoot };

export interface DocumentChangeBatch {
  protocol: "greenways.document/1";
  id: string;
  logId: string;
  sequence: string;
  previousEntryRoot?: LedgerRoot;
  baseRevisionRoot: LedgerRoot;
  baseAstRoot: LedgerRoot;
  expectedResultRoot: LedgerRoot;
  profileRoot: LedgerRoot;
  delegationRoot: LedgerRoot;
  operationRoots: LedgerRoot[];
  signature: string;
}

export interface DocumentSyncCheckpoint {
  documentId: string;
  environmentId: string;
  revisionRoot: LedgerRoot;
  astRoot: LedgerRoot;
  policyRoot: LedgerRoot;
  environmentSequence: string;
  packHex?: string;
}

export interface DocumentImportPreparation {
  challenge: string;
  checkpoint: DocumentSyncCheckpoint;
  authorized: boolean;
  maxOperations: 64;
  maxCells: 128;
  maxPackHexCharacters: 1000000;
}

export interface DocumentImportSubmission {
  challenge: string;
  documentId: string;
  contributorIdentity: string;
  logId: string;
  entries: DocumentChangeBatch[];
  personalHestiaReceipts: string[];
  packHex: string;
  cellCount: number;
}

export interface PublicDocumentReceipt {
  receiptId: string;
  environmentId: string;
  documentId: string;
  contributorIdentity: string;
  batchCount: number;
  operationCount: number;
  byteCount: number;
  receivedAt: string;
  outcome: "accepted" | "conflict" | "rejected" | "blocked";
  environmentSequence: string;
  submissionCommitment: string;
  resultCommitment?: string;
  environmentKey: string;
  signature: string;
}

export interface DocumentApprovalSubmission {
  stageId: string;
  policyRoot: LedgerRoot;
  revisionRoot: LedgerRoot;
  astRoot: LedgerRoot;
  decision: "approve" | "reject" | "withdraw";
  delegationRoot: LedgerRoot;
  signature: string;
}

export interface DocumentDeliverySubmission {
  policyRoot: LedgerRoot;
  revisionRoot: LedgerRoot;
  astRoot: LedgerRoot;
  cutoffSequence: string;
  coverageRoot: LedgerRoot;
  exporterRoot: LedgerRoot;
  disclosureMode: "public-full" | "authorized-full" | "commitment-only";
  artifacts: Array<{ id: string; mediaType: string; bytes: number; sha256: string }>;
  delegationRoot: LedgerRoot;
  signature: string;
}

export interface HestiaDocumentProtocolApi {
  syncDocument(documentId: string, fromRevision?: LedgerRoot): Promise<DocumentSyncCheckpoint>;
  prepareDocumentImport(documentId: string, metadata: object): Promise<DocumentImportPreparation>;
  importDocumentLog(documentId: string, submission: DocumentImportSubmission): Promise<PublicDocumentReceipt[]>;
  documentReceipt(receiptId: string): Promise<PublicDocumentReceipt>;
  approveDocument(documentId: string, approval: DocumentApprovalSubmission): Promise<{ approvalRoot: LedgerRoot }>;
  deliverDocument(documentId: string, delivery: DocumentDeliverySubmission): Promise<{ deliveryRoot: LedgerRoot }>;
}

export interface WorkspaceRefSigningRequest {
  address: LedgerRoot;
  sequence: number;
  workspace_id_root: LedgerRoot;
  scope: string;
  name: string;
  expected_root?: LedgerRoot;
  desired_root: LedgerRoot;
  intent_root: LedgerRoot;
  operation_root: LedgerRoot;
  signing_payload: string;
}

export type WorkspaceRefSubmission =
  | {
      status: "ok";
      address: LedgerRoot;
      sequence: number;
      scope: string;
      name: string;
      expected_root?: LedgerRoot;
      desired_root: LedgerRoot;
      ref_version: number;
      intent_root: LedgerRoot;
      transaction_root: LedgerRoot;
      receipt_root: LedgerRoot;
      result_root: LedgerRoot;
      state_root: LedgerRoot;
      block_root: LedgerRoot;
    }
  | {
      status: "conflict";
      error: "storage/ref-conflict";
      address: LedgerRoot;
      sequence: number;
      scope: string;
      name: string;
      expected_root?: LedgerRoot;
      actual_root?: LedgerRoot;
      desired_root: LedgerRoot;
      version: number;
      intent_root: LedgerRoot;
    };

export interface WorkspaceProposalSigningRequest extends WorkspaceRefSigningRequest {
  expected_root?: undefined;
  policy: "proposal-publication-v1";
}

export type WorkspaceProposalSubmission = WorkspaceRefSubmission & {
  policy: "proposal-publication-v1";
};

export interface LedgerDeveloperApi {
  genesis(network: string): Promise<{ block_root: LedgerRoot }>;
  createAccount(network: string, address: string): Promise<DeveloperAccount>;
  submitInteger(network: string, address: string, integer: string, costLimit?: number): Promise<DeveloperSubmission>;
  head(network: string): Promise<DeveloperHead>;
}

export interface LedgerSignedApi {
  registrationSigningRequest(network: string, publicKey: string): Promise<SignedRegistrationRequest>;
  registerAccount(network: string, publicKey: string, signature: string): Promise<SignedAccount>;
  integerSigningRequest(network: string, publicKey: string, integer: string, costLimit?: number): Promise<SignedIntegerRequest>;
  submitSignedInteger(network: string, publicKey: string, sequence: number, integer: string, signature: string, costLimit?: number): Promise<SignedSubmission>;
  documentHead(documentId: string): Promise<DocumentHead>;
  documentCreateSigningRequest(documentId: string, publicKey: string, syntaxRoot: LedgerRoot): Promise<SignedDocumentRequest>;
  createDocument(documentId: string, publicKey: string, syntaxRoot: LedgerRoot, signature: string): Promise<{ revision_root: LedgerRoot; document: DocumentHead }>;
  documentEditSigningRequest(documentId: string, baseRevision: LedgerRoot, publicKey: string, operationRoot: LedgerRoot): Promise<SignedDocumentRequest>;
  editDocument(documentId: string, baseRevision: LedgerRoot, publicKey: string, operationRoot: LedgerRoot, signature: string): Promise<{ revision_root: LedgerRoot; document: DocumentHead }>;
  submitOfflineDocumentCreate(submission: OfflineDocumentSubmission): Promise<{ revision_root: LedgerRoot; document: DocumentHead }>;
  submitOfflineDocumentEdit(submission: OfflineDocumentSubmission): Promise<{ revision_root: LedgerRoot; document: DocumentHead }>;
  submitOfflineTransaction(submission: OfflineTransactionSubmission): Promise<SignedSubmission & { result_root?: LedgerRoot; cost_used: number }>;
  workspaceRefSigningRequest(network: string, publicKey: string, workspaceIdRoot: LedgerRoot, expectedRoot: LedgerRoot | undefined, desiredRoot: LedgerRoot, costLimit?: number): Promise<WorkspaceRefSigningRequest>;
  submitWorkspaceRef(network: string, publicKey: string, sequence: number, workspaceIdRoot: LedgerRoot, expectedRoot: LedgerRoot | undefined, desiredRoot: LedgerRoot, signature: string, costLimit?: number): Promise<WorkspaceRefSubmission>;
  workspaceProposalSigningRequest(network: string, publicKey: string, workspaceIdRoot: LedgerRoot, desiredRoot: LedgerRoot, costLimit?: number): Promise<WorkspaceProposalSigningRequest>;
  submitWorkspaceProposal(network: string, publicKey: string, sequence: number, workspaceIdRoot: LedgerRoot, desiredRoot: LedgerRoot, signature: string, costLimit?: number): Promise<WorkspaceProposalSubmission>;
}
