(ns ledger.build-contract
  (:require [clojure.java.io :as io]))

(def ^:private contract
  "/* Generated by ledger.build-contract. Do not edit. */
export type LedgerRoot = string;

export interface DeveloperHead {
  network: string;
  height: number;
  block_root: LedgerRoot;
  state_root: LedgerRoot;
}

export interface DeveloperAccount {
  address: string;
  address_root: LedgerRoot;
  block_root: LedgerRoot;
  state_root: LedgerRoot;
}

export interface DeveloperSubmission {
  transaction_root: LedgerRoot;
  receipt_root: LedgerRoot;
  block_root: LedgerRoot;
  state_root: LedgerRoot;
  status: \"ok\" | \"error\";
}

export interface SignedRegistrationRequest {
  public_key: string;
  signing_payload: string;
}

export interface SignedAccount {
  address: LedgerRoot;
  public_key: string;
  block_root: LedgerRoot;
  state_root: LedgerRoot;
}

export interface SignedIntegerRequest {
  address: LedgerRoot;
  sequence: number;
  signing_payload: string;
}

export interface SignedSubmission extends DeveloperSubmission {
  address: LedgerRoot;
}

export interface DocumentHead {
  document_id: string;
  head_revision: LedgerRoot;
  syntax_root: LedgerRoot;
  next_order: number;
}

export interface SignedDocumentRequest {
  signing_payload: string;
}

export interface OfflineDocumentSubmission {
  documentId: string;
  nodeId: string;
  baseRevision?: LedgerRoot;
  syntaxRoot?: LedgerRoot;
  operationRoot?: LedgerRoot;
  publicKey: string;
  signature: string;
  packHex: string;
  cellCount: number;
}

export interface OfflineTransactionSubmission {
  network: string;
  sequence: number;
  operationRoot: LedgerRoot;
  formRoot: LedgerRoot;
  transactionRoot: LedgerRoot;
  runtimeRoot: LedgerRoot;
  publicKey: string;
  signature: string;
  costLimit: number;
  packHex: string;
  cellCount: number;
  operationManifest: Array<{
    root: LedgerRoot;
    kind: string;
    valueRoot?: LedgerRoot;
    symbolRoot?: LedgerRoot;
    depth?: number;
    index?: number;
    functionRoot?: LedgerRoot;
    childRoots: LedgerRoot[];
  }>;
  primitiveManifest: Array<{ root: LedgerRoot; id: string; arity: number }>;
}

export interface LedgerDeveloperApi {
  genesis(network: string): Promise<{ block_root: LedgerRoot }>;
  createAccount(network: string, address: string): Promise<DeveloperAccount>;
  submitInteger(network: string, address: string, integer: string, costLimit?: number): Promise<DeveloperSubmission>;
  head(network: string): Promise<DeveloperHead>;
}

export interface LedgerSignedApi {
  registrationSigningRequest(network: string, publicKey: string): Promise<SignedRegistrationRequest>;
  registerAccount(network: string, publicKey: string, signature: string): Promise<SignedAccount>;
  integerSigningRequest(network: string, publicKey: string, integer: string, costLimit?: number): Promise<SignedIntegerRequest>;
  submitSignedInteger(network: string, publicKey: string, sequence: number, integer: string, signature: string, costLimit?: number): Promise<SignedSubmission>;
  documentHead(documentId: string): Promise<DocumentHead>;
  documentCreateSigningRequest(documentId: string, publicKey: string, syntaxRoot: LedgerRoot): Promise<SignedDocumentRequest>;
  createDocument(documentId: string, publicKey: string, syntaxRoot: LedgerRoot, signature: string): Promise<{ revision_root: LedgerRoot; document: DocumentHead }>;
  documentEditSigningRequest(documentId: string, baseRevision: LedgerRoot, publicKey: string, operationRoot: LedgerRoot): Promise<SignedDocumentRequest>;
  editDocument(documentId: string, baseRevision: LedgerRoot, publicKey: string, operationRoot: LedgerRoot, signature: string): Promise<{ revision_root: LedgerRoot; document: DocumentHead }>;
  submitOfflineDocumentCreate(submission: OfflineDocumentSubmission): Promise<{ revision_root: LedgerRoot; document: DocumentHead }>;
  submitOfflineDocumentEdit(submission: OfflineDocumentSubmission): Promise<{ revision_root: LedgerRoot; document: DocumentHead }>;
  submitOfflineTransaction(submission: OfflineTransactionSubmission): Promise<SignedSubmission & { result_root?: LedgerRoot; cost_used: number }>;
}
")

(defn build-contract []
  (let [path (io/file "contracts" "ledger-client" "generated.ts")]
    (.mkdirs (.getParentFile path))
    (spit path contract)
    (println "Wrote" (.getPath path))))

(defn -main [& _]
  (build-contract))
