(ns gwdb.ledger.base
  (:require [tahto.core :as l]
            [postgres.core :as pg]
            [gwdb.ledger.schema]
            [gwdb.ledger.type]
            [gwdb.ledger.codec]
            [gwdb.ledger.crypto]
            [gwdb.ledger.cell]
            [gwdb.ledger.scoped-ref]
            [gwdb.ledger.workspace]
            [gwdb.ledger.codec-value]
            [gwdb.ledger.value]
            [gwdb.ledger.syntax]
            [gwdb.ledger.state]
            [gwdb.ledger.account]
            [gwdb.ledger.op]
            [gwdb.ledger.context]
            [gwdb.ledger.primitive]
            [gwdb.ledger.runtime-profile]
            [gwdb.ledger.runtime]
            [gwdb.ledger.function]
            [gwdb.ledger.protocol]
            [gwdb.ledger.actor]
            [gwdb.ledger.contract]
            [gwdb.ledger.runtime-support]
            [gwdb.ledger.account-runtime]
            [gwdb.ledger.runtime-v2]
            [gwdb.ledger.actor-runtime]
            [gwdb.ledger.contract-runtime]
            [gwdb.ledger.protocol-runtime]
            [gwdb.ledger.module]
            [gwdb.ledger.iterator]
            [gwdb.ledger.transaction]
            [gwdb.ledger.block]
            [gwdb.ledger.snapshot]
            [gwdb.ledger.integrity]
            [gwdb.ledger.admission]
            [gwdb.ledger.developer]))

;; The ledger is deliberately a plain PostgreSQL project. Supabase transforms,
;; RPC metadata and application schemas do not participate in this protocol.
(l/script :postgres
  {:require [[postgres.core :as pg]
             [gwdb.ledger.type]
             [gwdb.ledger.codec]
             [gwdb.ledger.crypto]
             [gwdb.ledger.cell]
             [gwdb.ledger.scoped-ref]
             [gwdb.ledger.workspace]
             [gwdb.ledger.codec-value]
             [gwdb.ledger.value]
             [gwdb.ledger.syntax]
             [gwdb.ledger.state]
             [gwdb.ledger.account]
             [gwdb.ledger.op]
             [gwdb.ledger.context]
             [gwdb.ledger.primitive]
             [gwdb.ledger.runtime-profile]
             [gwdb.ledger.runtime]
             [gwdb.ledger.function]
             [gwdb.ledger.protocol]
             [gwdb.ledger.actor]
             [gwdb.ledger.contract]
             [gwdb.ledger.runtime-support]
             [gwdb.ledger.account-runtime]
             [gwdb.ledger.runtime-v2]
             [gwdb.ledger.actor-runtime]
             [gwdb.ledger.contract-runtime]
             [gwdb.ledger.protocol-runtime]
             [gwdb.ledger.module]
             [gwdb.ledger.iterator]
             [gwdb.ledger.transaction]
             [gwdb.ledger.block]
             [gwdb.ledger.snapshot]
             [gwdb.ledger.integrity]
             [gwdb.ledger.admission]
             [gwdb.ledger.developer]]
   :config {:dbname "gw-ledger-test"}
   :import [["pgcrypto"]]
   :static {:application ["gw"]
            :seed ["gw_ledger"]
            :all {:schema ["gw_ledger"]}}})

(defonce +run+ [])
